# Generated by Django 5.0.6 on 2024-10-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_coupons_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='end_date',
            field=models.DateField(blank=True, default='2024-12-12', null=True, verbose_name='Дата конца'),
        ),
    ]
