# Generated by Django 5.0.6 on 2024-05-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_carts_delete_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='carts',
            name='pizzas',
            field=models.JSONField(default=dict),
        ),
    ]
