# Generated by Django 5.0.6 on 2024-05-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_carts_pizzas_carts_pizzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='image',
            field=models.ImageField(default='main/static/images/blank_pizza.png', upload_to='', verbose_name='Изображение'),
        ),
    ]
