# Generated by Django 5.0.6 on 2024-05-15 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_address_alter_carts_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Готовность заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='lead_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время заказа'),
        ),
    ]
