# Generated by Django 5.0.6 on 2024-05-28 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время заказа')),
                ('answer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время заказа')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
        ),
    ]
