# Generated by Django 5.0.6 on 2024-05-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_faqs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='faqs',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Закрыт'),
        ),
    ]
